version: "3"

services:
  jupyter:
    build: .
    image: ebisma/cruzhacks
    volumes:
      - .:/home/jovyan/
    ports:
      - "8888:8888"
    environment:
      - SPARK_CLASSPATH=/home/jovyan/spark_jdbc/spark_jdbc.jar
